twig:
    default_path: '%kernel.project_dir%/templates'
    
    paths:
        # point this wherever your css files live
        '%kernel.project_dir%/public/assets/css': css
        '%kernel.project_dir%/public/upload/img/photos': photos

when@test:
    twig:
        strict_variables: true
