controllers:
    prefix: "{_locale}"
    requirements: 
        _locale: en|fr
    defaults:
        _locales: fr
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
redirect:
   path: /
   controller: App\Controller\RedirectController::redirectToLocale
